### ISSUE TITLE
Add: Documentation

### ISSUE THREAD

**Issue by yube01** [yube01/google-drive-clone#1]
Add documentation for this project

**Comment by ghost** [comment]
@yube01 Could you tell me what documentation do u expect? Also guidelines on how to run the project

**Comment by yube01** [comment]
In frontend, I have used vite so to run this program you can simply type npm run dev and for backend , I have used express js and to run this program to need to type npm run dev as well and both need to run simultaneously to perform all kinds of tasks

Link : [google-drive-clones.netlify.app/](https://google-drive-clones.netlify.app/)
I have uploaded live version of this program in server so based on your experience you can maintain document of this program

There isn't any specific documentation guideline from my side so feel free to make document based on your experience while using this program
 

Also make branch name documentation before requesting for pull request

**Comment by ghost** [comment]
hey it did run on my local server but when i sign up the pop up says user hasnt been created although i already had signed up.

**Comment by ghost** [comment]
I would need to checkout for documentation right, guide me plz

**Comment by yube01** [comment]
Follow these steps

Create a new Branch

git checkout -b my-new-branch

Changes : Create a new branch and commit your changes on that branch. Follow the How to contribute

ADD and COMMIT

Add your changes
git add .
Commit your changes.
git commit -m "Relevant message"

Push : After all changes are commited, push your changes to your remote repo.

git push -u origin my-new-branch
